"""Final cleanup of bill_part table by dropping percentage column

Revision ID: 1fcedaa178af
Revises: b31b41c0e4b8
Create Date: 2024-03-29 17:30:12.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fcedaa178af'
down_revision: Union[str, None] = 'b31b41c0e4b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bill_part', 'percentage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill_part', sa.Column('percentage', sa.NUMERIC(precision=5, scale=2), nullable=False))
    # ### end Alembic commands ###
