"""Add profile_image_url to users table

Revision ID: 4a92f3cde7d9
Revises: 1fcedaa178af
Create Date: 2025-06-09 14:24:52.582193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4a92f3cde7d9'
down_revision: Union[str, None] = '1fcedaa178af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bill_part', 'amount_owed',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.add_column('users', sa.Column('profile_image_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'profile_image_url')
    op.alter_column('bill_part', 'amount_owed',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###
