"""add bill category table

Revision ID: 7c9719cbe5a2
Revises: a1001cfc7236
Create Date: 2025-06-10 00:56:23.378601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c9719cbe5a2'
down_revision: Union[str, None] = 'a1001cfc7236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['users_groups.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('group_id', 'name', name='uq_group_category_name')
    )
    op.create_index(op.f('ix_bill_categories_category_id'), 'bill_categories', ['category_id'], unique=False)
    op.add_column('bills', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bills', 'bill_categories', ['category_id'], ['category_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bills', type_='foreignkey')
    op.drop_column('bills', 'category_id')
    op.drop_index(op.f('ix_bill_categories_category_id'), table_name='bill_categories')
    op.drop_table('bill_categories')
    # ### end Alembic commands ###
