"""Minor naming change: bill_creator to created_by in Bill

Revision ID: 7ef412d28d41
Revises: caa8b87a421e
Create Date: 2025-05-12 18:00:50.857700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7ef412d28d41'
down_revision: Union[str, None] = 'caa8b87a421e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bills_ibfk_1', 'bills', type_='foreignkey')
    op.drop_column('bills', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('bills_ibfk_1', 'bills', 'users', ['created_by'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###
