"""minor change friendship table: no more req_id < add_id

Revision ID: 904d94f1b6da
Revises: 360f52cfa4f9
Create Date: 2025-06-07 00:41:33.772347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '904d94f1b6da'
down_revision: Union[str, None] = '360f52cfa4f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_friendship_order', 'friendships', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('check_friendship_order', 'friendships', 'requester_id < addressee_id')
    # ### end Alembic commands ###
