"""add audit_log_entries table

Revision ID: 92bfafce088f
Revises: 0df44a624510
Create Date: 2025-05-19 17:23:52.821080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92bfafce088f'
down_revision: Union[str, None] = '0df44a624510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.Enum('BILL_CREATED', 'bill_updateD', 'BILL_DELETED', 'PAYMENT_CREATED', 'PAYMENT_UPDATED', 'PAYMENT_DELETED', 'MEMBER_INVITED', 'MEMBER_JOINED', 'MEMBER_LEFT', 'MEMBER_REMOVED', 'MEMBER_ROLE_UPDATED', 'GROUP_CREATED', 'GROUP_DETAILS_UPDATED', name='auditactiontype'), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('target_bill_id', sa.Integer(), nullable=True),
    sa.Column('target_payment_id', sa.Integer(), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('summary_message', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['users_groups.group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_bill_id'], ['bills.bill_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_payment_id'], ['payments.payment_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entries_action_type'), 'audit_log_entries', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_group_id'), 'audit_log_entries', ['group_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_id'), 'audit_log_entries', ['id'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_target_bill_id'), 'audit_log_entries', ['target_bill_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_target_payment_id'), 'audit_log_entries', ['target_payment_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_target_user_id'), 'audit_log_entries', ['target_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_entries_target_user_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_target_payment_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_target_bill_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_group_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_action_type'), table_name='audit_log_entries')
    op.drop_table('audit_log_entries')
    # ### end Alembic commands ###
