"""Minor changes

Revision ID: aeab26d5c639
Revises: d3a086ab0d7b
Create Date: 2025-05-08 01:17:39.166823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aeab26d5c639'
down_revision: Union[str, None] = 'd3a086ab0d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_date', sa.Date(), nullable=False))
    op.add_column('payments', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('transactions', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_column('transactions', 'note')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('note', mysql.TEXT(), nullable=True))
    op.drop_column('transactions', 'notes')
    op.drop_column('payments', 'notes')
    op.drop_column('payments', 'payment_date')
    # ### end Alembic commands ###
