"""revert

Revision ID: b3bd82e5efa6
Revises: 7ef412d28d41
Create Date: 2025-05-12 18:04:22.385342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3bd82e5efa6'
down_revision: Union[str, None] = '7ef412d28d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bills', 'users', ['created_by'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bills', type_='foreignkey')
    op.drop_column('bills', 'created_by')
    # ### end Alembic commands ###
