"""Add InitialPayment table and modify Bill table for accurate payment tracking

Revision ID: d3a086ab0d7b
Revises: 4036e688b4bd
Create Date: 2025-04-28 01:16:21.060189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3a086ab0d7b'
down_revision: Union[str, None] = '4036e688b4bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('initial_payments',
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('amount_paid > 0', name='check_initial_payment_positive'),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.bill_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('bill_id', 'user_id')
    )
    op.drop_constraint('bill_part_ibfk_1', 'bill_part', type_='foreignkey')
    op.create_foreign_key(None, 'bill_part', 'bills', ['bill_id'], ['bill_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bill_part', type_='foreignkey')
    op.create_foreign_key('bill_part_ibfk_1', 'bill_part', 'bill_items', ['bill_id'], ['bill_id'], ondelete='CASCADE')
    op.drop_table('initial_payments')
    # ### end Alembic commands ###
