"""add bill categories table and link to bills

Revision ID: da121b1aebfb
Revises: ea2503805170
Create Date: 2025-06-10 00:31:24.438419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da121b1aebfb'
down_revision: Union[str, None] = 'ea2503805170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('icon_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_bill_categories_id'), 'bill_categories', ['id'], unique=False)
    op.add_column('bills', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bills', 'bill_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bills', type_='foreignkey')
    op.drop_column('bills', 'category_id')
    op.drop_index(op.f('ix_bill_categories_id'), table_name='bill_categories')
    op.drop_table('bill_categories')
    # ### end Alembic commands ###
