"""add notifications table

Revision ID: dcba13b65c3e
Revises: b3bd82e5efa6
Create Date: 2025-05-16 00:03:51.070927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcba13b65c3e'
down_revision: Union[str, None] = 'b3bd82e5efa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notification_type', sa.Enum('group_invite', 'new_bill', 'bill_update', 'member_added_to_group', name='notificationtype'), nullable=True),
    sa.Column('related_group_id', sa.Integer(), nullable=True),
    sa.Column('related_bill_id', sa.Integer(), nullable=True),
    sa.Column('related_payment_id', sa.Integer(), nullable=True),
    sa.Column('related_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_bill_id'], ['bills.bill_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_group_id'], ['users_groups.group_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_payment_id'], ['payments.payment_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_user_id'), 'notifications', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_notifications_related_bill_id'), 'notifications', ['related_bill_id'], unique=False)
    op.create_index(op.f('ix_notifications_related_group_id'), 'notifications', ['related_group_id'], unique=False)
    op.create_index(op.f('ix_notifications_related_payment_id'), 'notifications', ['related_payment_id'], unique=False)
    op.create_index(op.f('ix_notifications_related_user_id'), 'notifications', ['related_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_related_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_payment_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_group_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_bill_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
