"""minor naming change to AuditActionType

Revision ID: e45294584bc2
Revises: 92bfafce088f
Create Date: 2025-05-20 23:33:08.496037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e45294584bc2'
down_revision: Union[str, None] = '92bfafce088f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log_entries', 'action_type',
               existing_type=mysql.ENUM('BILL_CREATED', 'BILL_UPDATED', 'BILL_DELETED', 'PAYMENT_CREATED', 'PAYMENT_UPDATED', 'PAYMENT_DELETED', 'MEMBER_INVITED', 'MEMBER_JOINED', 'MEMBER_LEFT', 'MEMBER_REMOVED', 'MEMBER_ROLE_UPDATED', 'GROUP_CREATED', 'GROUP_DETAILS_UPDATED'),
               type_=sa.Enum('BILL_CREATED', 'BILL_UPDATED', 'BILL_DELETED', 'PAYMENT_CREATED', 'PAYMENT_UPDATED', 'PAYMENT_DELETED', 'MEMBER_INVITED', 'MEMBER_ADDED', 'MEMBER_LEFT', 'MEMBER_REMOVED', 'MEMBER_ROLE_UPDATED', 'GROUP_CREATED', 'GROUP_DETAILS_UPDATED', name='auditactiontype'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log_entries', 'action_type',
               existing_type=sa.Enum('BILL_CREATED', 'BILL_UPDATED', 'BILL_DELETED', 'PAYMENT_CREATED', 'PAYMENT_UPDATED', 'PAYMENT_DELETED', 'MEMBER_INVITED', 'MEMBER_ADDED', 'MEMBER_LEFT', 'MEMBER_REMOVED', 'MEMBER_ROLE_UPDATED', 'GROUP_CREATED', 'GROUP_DETAILS_UPDATED', name='auditactiontype'),
               type_=mysql.ENUM('BILL_CREATED', 'BILL_UPDATED', 'BILL_DELETED', 'PAYMENT_CREATED', 'PAYMENT_UPDATED', 'PAYMENT_DELETED', 'MEMBER_INVITED', 'MEMBER_JOINED', 'MEMBER_LEFT', 'MEMBER_REMOVED', 'MEMBER_ROLE_UPDATED', 'GROUP_CREATED', 'GROUP_DETAILS_UPDATED'),
               existing_nullable=False)
    # ### end Alembic commands ###
