"""Add joined_at and left_at to GroupMember (changed from GroupMembers)

Revision ID: ff7e5eaa8293
Revises: dcba13b65c3e
Create Date: 2025-05-16 23:41:44.146184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff7e5eaa8293'
down_revision: Union[str, None] = 'dcba13b65c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_members', sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('group_members', sa.Column('left_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_members', 'left_at')
    op.drop_column('group_members', 'joined_at')
    # ### end Alembic commands ###
